kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 9800
    protocol: TCP
  - containerPort: 443
    hostPort: 44300
    protocol: TCP
- role: worker   # worker 1: esegue i pod applicativi
- role: worker   # worker 2: esegue i pod applicativi (ridondanza e bilanciamento)
